<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"房东管理",
			            "menuJump":"列表",
			            "tableName":"fangdong"
			        }
			    ],
			    "menu":"房东管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋出售管理",
                        "menuJump":"列表",
                        "tableName":"chushou"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋出售留言管理",
                        "menuJump":"列表",
                        "tableName":"chushouLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"房屋出售订单管理",
                        "menuJump":"列表",
                        "tableName":"chushouOrder"
                    }
                ],
                "menu":"房屋出售管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋出租管理",
                        "menuJump":"列表",
                        "tableName":"chuzu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"房屋出租留言管理",
                        "menuJump":"列表",
                        "tableName":"chuzuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"房屋出租订单管理",
                        "menuJump":"列表",
                        "tableName":"chuzuOrder"
                    }
                ],
                "menu":"房屋出租管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"户型类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuixing"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }

                ],
                "menu":"基础数据管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告管理"
            }
            
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	       {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"房屋出售管理",
	                    "menuJump":"列表",
	                    "tableName":"chushou"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "修改"
	                    ],
	                    "menu":"房屋出售留言管理",
	                    "menuJump":"列表",
	                    "tableName":"chushouLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"房屋出售订单管理",
	                    "menuJump":"列表",
	                    "tableName":"chushouOrder"
	                }
	            ],
	            "menu":"房屋出售管理"
	        }
	       ,{
	           "child":[
	               {
	                   "buttons":[
	                       "查看",
	                       "新增",
	                       "修改",
	                       "删除"
	                   ],
	                   "menu":"房屋出租管理",
	                   "menuJump":"列表",
	                   "tableName":"chuzu"
	               }
	               ,
	               {
	                   "buttons":[
	                       "查看",
	                       "修改"
	                   ],
	                   "menu":"房屋出租留言管理",
	                   "menuJump":"列表",
	                   "tableName":"chuzuLiuyan"
	               }
	               ,
	               {
	                   "buttons":[
	                       "查看"
	                   ],
	                   "menu":"房屋出租订单管理",
	                   "menuJump":"列表",
	                   "tableName":"chuzuOrder"
	               }
	           ],
	           "menu":"房屋出租管理"
	       }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告管理"
	        }
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"房东",
	    "tableName":"fangdong"
	}
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"房屋出售管理",
	                    "menuJump":"列表",
	                    "tableName":"chushou"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"房屋出售留言管理",
	                    "menuJump":"列表",
	                    "tableName":"chushouLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"房屋出售订单管理",
	                    "menuJump":"列表",
	                    "tableName":"chushouOrder"
	                }
	            ],
	            "menu":"房屋出售管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"房屋出租管理",
	                    "menuJump":"列表",
	                    "tableName":"chuzu"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"房屋出租留言管理",
	                    "menuJump":"列表",
	                    "tableName":"chuzuLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "退房"
	                    ],
	                    "menu":"房屋出租订单管理",
	                    "menuJump":"列表",
	                    "tableName":"chuzuOrder"
	                }
	            ],
	            "menu":"房屋出租管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告管理"
	        }
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
